config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "signup"  => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  namespace :admin do
    resources :users, except: [:new, :create, :show]
    resources :categories
    resources :words
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy

  validates :word_detail, presence: true, length: {maximum: Settings.size_word}
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :verify_admin, only: :destroy
  before_action :logged_in_user
  before_action :load_word, only: [:edit, :update, :destroy]
  before_action :load_categories

  def index
    @category = Category.find_by id: params[:category_id]
    if @category
      flash[:danger] = t "admin_load_fails_category"
      redirect_to new_admin_word_path
    end
    @words = Word.paginate page: params[:page],
      per_page: Settings.per_page.words
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.create word_params
    if @word.save
      flash[:success] = t "create_words_success"
      redirect_to admin_words_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "update_success"
      redirect_to admin_words_path
    else
      render :edit
    end
  end

  def destroy
    if @word.destroy
      flash[:success] = t "word_delete"
    else
      flash[:danger] = t "unsuccess_delete"
    end
    redirect_to admin_words_path
  end

  private
  def word_params
    params.require(:word).permit :word_detail, :category_id
  end

  def load_categories
    @categories = Category.all
  end

  def load_word
    @word = Word.find_by id: params[:id]
    render_404 if @word.nil?
  end
end

app/views/admin/words/edit.html.erb
<% provide :title, t("update_words") %>
<% provide :button_text, t("save_changes") %>
<h1><%= t "update_words" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @word] do |f| %>
      <%= f.collection_select :category_id, @categories, :id,:name %>

      <%= f.label :word_detail %>
      <%= f.text_field :word_detail, class: "form-control" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, t("all_words") %>
<h1><%= t ("all_words") %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= link_to t("create_words"), new_admin_word_path, class: "btn btn-primary" %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%= t "stt" %></th>
          <th><%= t "name" %></th>
          <th><%= t "category_name" %></th>
          <th><%= t "action" %></th>
        </tr>
      </thead>
      <tbody>
      <% @words.each do |word| %>
        <tr>
          <td><%= word.id %></td>
          <td><%= word.word_detail %></td>
          <td><%= word.category.name %></td>
          <td>
            <%= link_to t("edit"), edit_admin_word_path(word),
              class: "btn btn-primary" %>
            <%= link_to t("delete"), admin_word_path(word),
              method: :delete, data: {confirm: "message_delete" },
              class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate %>
  </div>
</div>

app/views/admin/words/new.html.erb
<% provide :title, t("create_words") %>
<% provide :button_text, t("create_words") %>
<h1><%= t "create_words" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @word] do |f| %>
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, @categories, :id, :name %>

      <%= f.label :word_detail %>
      <%= f.text_field :word_detail, class: "form-control" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>