config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "signup"  => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  namespace :admin do
    resources :users, except: [:new, :create, :show]
    resources :categories
    resources :words
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lessons, dependent: :destroy
  has_many :activity, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_save {self.email = email.downcase}

  validates :name, presence: true, length: {maximum:50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  def is_user? user
    self == user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :load_user, only: [:edit, :update, :destroy]
  before_action :verify_admin, only: :destroy
  before_action :logged_in_user

  def index
    @users = User.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "profile_updated"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "deleted_user"
    else
      flash[:danger] = t "unsuccess_delete"
    end
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit :is_admin, :name, :email, :password,
      :password_confirmation
  end

  def load_user
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "not_found"
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate page: params[:page], per_page: Settings.per_page.user
  end

  def show
    @user = User.find_by id: params[:id]
    unless @user
      flash[:danger] = t "no_user"
      redirect_to root_url
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "sign_up_success"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "profile_update"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = t "please_login"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find_by id: params[:id]
    render file: Settings.page_404_url unless current_user.is_user? @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: Settings.size_users_helpers}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/admin/users/_admin_user.html.erb
<% @users.each do |user| %>
  <tr>
    <td><%= gravatar_for user, Settings.normal_avatar %></td>
    <td><%= link_to user.name, user %></td>
    <td>
      <%= link_to [:admin, user], method: :delete, data: {confirm: t("message_delete")} do %>
        <span class="glyphicon glyphicon-trash" title="Delete"></span>
      <% end %>
    </td>
    <td>
      <%= link_to edit_admin_user_path(user) do %>
        <span class="glyphicon glyphicon-edit" title="Edit"></span>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/admin/users/edit.html.erb
<% provide :title, t("edit_user") %>
<div class="row fix_box">
  <h1><%= t("edit_user") %></h1>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @user] do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("submit"), class: "btn btn-primary center" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t("change"), "http://gravatar.com/emails", target: "_blank" %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t("all_users") %>
<div class="fix_box">
  <h1><%= t("all_users") %></h1>
  <ul class="users">
    <table class="table">
      <thead class="table-title">
        <tr>
          <td><%= t "avatar" %></td>
          <td><%= t "user_name" %></td>
          <td><%= t "action" %></td>
        </tr>
      </thead>
      <tbody>
        <%= render "admin_user" %>
      </tbody>
    </table>
  </ul>
  <div class="center"><%= will_paginate %></div>
</div>