config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "signup"  => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  namespace :admin do
    resources :users, except: [:new, :create, :show]
    resources :categories
    resources :words
  end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <a href= "">
      <%= t "facebook" %>
    </a>
  </small>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("e_learning"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to t("users"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle": "dropdown"} do %>
              <%= t("account") %> <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), current_user %></li>
              <li><%= link_to "settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("sign_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("log_in"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": true %>
    <%= javascript_include_tag "application", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>